version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:12.14.1"
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm run test:ci
          environment:
            stg_NETWORK: ropsten
      - deploy:
          name: deploy-staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/deploy_staging.sh
            fi
      - deploy:
          name: deploy-production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/deploy_production.sh
            fi
